services:
  guestservice:
    container_name: guest_green_container
    image: academyitwill/guest:v4 # 도커 허브에서 앱 이미지 사용
    environment:
      SPRING_PROFILES_ACTIVE: mysql-prod-group   # ★ 프로필 분리됨
    #depends_on:
    #  - mysqlservice.default
    ports:
      - 80:8080
    networks:
      - guest_network  
    restart: on-failure 
volumes:
  mysql_volume:
    external: true
networks:
  guest_network:
    external: true    
    

